# Configuration for the CVAE model training on drug-induced gene expression prediction
hidden_dim: 256
num_encoder_layers: 0
encoder_dropout: 0.1

latent_dim: 128

num_decoder_layers: 0
decoder_dropout: 0.3

condition_emb_dim: 128
num_molecular_emb_layers: 0

alpha: 100
beta: 0.5
beta_anneal: False  # Enable beta annealing
gamma: 0.1

num_epochs: 10
learning_rate: 0.00005
model_save_dir: "models/drug_induced_gene_expression_prediction"